refactor: stop action to use mode live or analyze
Signed-off-by: Lorenzo Susini <susinilorenzo1@gmail.com>

diff --git a/stop/action.yaml b/stop/action.yaml
--- a/stop/action.yaml
+++ b/stop/action.yaml
@@ -2,25 +2,10 @@ name: 'Falco Action Stop'
 description: 'Run Falco in a GitHub Action'
 author: 'The Falco Authors'
 inputs:
-  custom-rule-file:
-    description: 'Custom rule file'
+  mode:
+    description: 'Stop action with a mode. Can be live or analyze'
     required: false
-    default: ''
-  filters-config:
-    description: 'Filter configuration file'
-    required: false
-    default: 'src/filters.config'
-  save-capture:
-    description: "Save Files on S3?"
-    type: boolean
-    default: false
-  openai-model:
-    description: "Open AI model to use for summary"
-    type: sting
-    default: "gpt-3.5-turbo"
-  openai-user-prompt:
-    description: "Message to send to OpenAI"
-    type: string
+    default: 'live'
   verbose:
     description: "Enable verbose logs"
     type: boolean
@@ -28,137 +13,36 @@ inputs:
 runs:
   using: 'composite'
   steps:
-  - name: Stop Sysdig capture
+  - name: Validate mode
     shell: bash
     run: |
-      echo "Stopping Sysdig"
-      docker stop sysdig
-      echo "Sysdig stopped"
+      if [[ "${{ inputs.mode }}" != "live" && "${{ inputs.mode }}" != "analyze" ]]; then
+        echo "Invalid mode. Must be either live or analyze"
+        exit 1
+      fi
   
-  - name: Start Falco in capture mode
+  - name: Stop Falco or Sysdig containers
     shell: bash
     run: |
-      MOUNT_CUSTOM_RULE=""
-      if [[ -f "${{inputs.custom-rule-file}}" ]]; then
-        if [ "${{ inputs.verbose }}" = "true" ]; then
-          echo "Loading custom rules from ${{inputs.custom-rule-file}}"
-        fi
-        MOUNT_CUSTOM_RULE="-v ${{inputs.custom-rule-file}}:/etc/falco/rules.d/custom_rules.yaml"
+      echo "Stopping containers"
+      falco=$(docker ps --format '{{.Names}}' | grep -o falco)
+      if [[ ! -z "$falco" ]]; then
+        docker stop falco
       fi
-
-      docker run --rm --name falco \
-        -v /tmp:/tmp \
-        $MOUNT_CUSTOM_RULE \
-        falcosecurity/falco-no-driver:latest falco -o "json_output=true" -o "file_output.enabled=true" -o "file_output.keep_alive=false" -o "file_output.filename=/tmp/falco_events.json" -o "engine.kind=replay" -o "engine.replay.capture_file=/tmp/capture.scap" 
-
-  - name: Extract outbound connections
-    shell: bash
-    env:
-      VERBOSE: ${{ inputs.verbose }}
-    run: |
-      OUTBOUND_FILTER="(((evt.type = connect and evt.dir=<) or (evt.type in (sendto,sendmsg,sendmmsg) and evt.dir=< and fd.l4proto != tcp and fd.connected=false and fd.name_changed=true)) and (fd.typechar = 4 or fd.typechar = 6) and (fd.ip != \"0.0.0.0\" and fd.net != \"127.0.0.0/8\" and not fd.snet in (\"10.0.0.0/8\", \"172.16.0.0/12\", \"192.168.0.0/16\")))" 
-      CUSTOM_FILTERS=$(jq -r '.outbound_connections // [] | .[] | "and not (\(.condition) )"' "${{github.action_path}}/${{inputs.filters-config}}" | sed "s/'/\"/g" | tr '\n' ' ' | sed 's/[[:space:]]*$//')
-      if [ "${{ inputs.verbose }}" = "true" ]; then
-        echo "Custom filters: $CUSTOM_FILTERS"
+      sysdig=$(docker ps --format '{{.Names}}' | grep -o sysdig)
+      if [[ ! -z "$sysdig" ]]; then
+        docker stop sysdig
       fi
-      OUTBOUND_OUTPUT="%fd.sip,%fd.sport,%proc.name,%proc.exepath,%user.name"
-      ${{github.action_path}}/src/run_sysdig.sh filter "/tmp/capture.scap" "$OUTBOUND_FILTER $CUSTOM_FILTERS" "$OUTBOUND_OUTPUT" "/tmp/outbound.txt"
-
-  - name: Extract written files
-    shell: bash
-    env:
-      VERBOSE: ${{ inputs.verbose }}
-    run: |
-      FILE_WRITTEN_FILTER="evt.type in (open,openat,openat2) and evt.is_open_write=true and fd.typechar=\"f\" and fd.num>=0"
-      CUSTOM_FILTERS=$(jq -r '.written_files // [] | .[] | "and not (\(.condition) )"' "${{github.action_path}}/${{inputs.filters-config}}" | sed "s/'/\"/g" | tr '\n' ' ' | sed 's/[[:space:]]*$//')
-      if [ "${{ inputs.verbose }}" = "true" ]; then
-        echo "Custom filters: $CUSTOM_FILTERS"
-      fi
-      FILE_WRITTEN_OUTPUT="%fd.name,%proc.name,%proc.exepath,%proc.pexepath,%user.name"
-      ${{github.action_path}}/src/run_sysdig.sh filter "/tmp/capture.scap" "$FILE_WRITTEN_FILTER $CUSTOM_FILTERS" "$FILE_WRITTEN_OUTPUT" "/tmp/files_written.txt"
-
-  - name: Extract processes information
-    shell: bash
-    env:
-      VERBOSE: ${{ inputs.verbose }}
-    run: |
-      PROC_FILTER="evt.type in (execve, execveat) and evt.dir=< and evt.arg.res=0"
-      CUSTOM_FILTERS=$(jq -r '.processes // [] | .[] | "and not (\(.condition) )"' "${{github.action_path}}/${{inputs.filters-config}}" | sed "s/'/\"/g" | tr '\n' ' ' | sed 's/[[:space:]]*$//')
-      if [ "${{ inputs.verbose }}" = "true" ]; then
-        echo "Custom filters: $CUSTOM_FILTERS"
-      fi
-      PROC_FILTER_OUTPUT="%proc.name,%proc.exepath,%proc.pname,%proc.pexepath,%user.name"
-      ${{github.action_path}}/src/run_sysdig.sh filter "/tmp/capture.scap" "$PROC_FILTER $CUSTOM_FILTERS" "$PROC_FILTER_OUTPUT" "/tmp/proc.txt"
-
-  - name: Extract chisels information for summary
-    shell: bash
-    env:
-      VERBOSE: ${{ inputs.verbose }}
-    run: |
-      ${{github.action_path}}/src/run_sysdig.sh chisel "/tmp/capture.scap" "udp_extract.lua" "/tmp/udp_extract.txt"
-      ${{github.action_path}}/src/run_sysdig.sh chisel "/tmp/capture.scap" "topconns.lua" "/tmp/top_connection.txt"
-      ${{github.action_path}}/src/run_sysdig.sh chisel "/tmp/capture.scap" "topprocs_net.lua" "/tmp/topprocs_net.txt"
-
-  - name: Extract DNS domains
-    shell: bash
-    env:
-      VERBOSE: ${{ inputs.verbose }}
-    run: |
-      DNS_FILTER="evt.type in (recvmsg,read,recv,recvfrom) and fd.rport=53 and fd.l4proto=udp"
-      DNS_OUTPUT="%evt.buffer"
-      ${{github.action_path}}/src/run_sysdig.sh filter "/tmp/capture.scap" "$DNS_FILTER" "$DNS_OUTPUT" "/tmp/buffers.txt"
-      if [[ ! -s /tmp/buffers.txt ]]; then
-        echo "Warning: No contacted DNS domains found"
-        exit 0
-      fi
-      cat /tmp/buffers.txt | grep -o -E "[a-zA-Z0-9-]+(\.[a-zA-Z0-9-]+)*(\.[a-zA-Z]{2,})" | grep -E -v "NULL" | grep -E -v "ns." | grep -E -v "\->" | grep -E -v "evt.buffer" | sort | uniq > /tmp/dns_extract.txt
-      if [[ "${{ inputs.verbose }}" == "true" ]]; then
-        echo "Extracted DNS domains" && cat /tmp/dns_extract.txt
-      fi
-      while read -r line; do
-        echo "{ \"domain\": \"$line\" }"
-      done < /tmp/dns_extract.txt > /tmp/dns_extract_json.txt
   
-  - name: Extract executables' hash
-    shell: bash
-    env:
-      VERBOSE: ${{ inputs.verbose }}
-    run: |      
-      cat /tmp/proc.txt| jq '."proc.exepath"' | tr -d "\"" | while read -r file; do
-        if [ -f "$file" ]; then
-            line=$(sha256sum "$file")
-            sha=$(echo "$line" | awk '{print $1}')
-            file=$(echo "$line" | awk '{print $2}')
-            echo "{ \"sha256\": \"$sha\", \"filename\": \"$file\" }"
-        else
-            echo "Warning: File $file does not exist anymore when extracting its SHA256 hash" >&2
-        fi 
-      done > /tmp/hashes.txt
-
-      sort -u -o /tmp/hashes.txt /tmp/hashes.txt
-  
-  - name: Extract docker container images
-    shell: bash
-    env:
-      VERBOSE: ${{ inputs.verbose }}
-    run: |
-      CONTAINER_FILTER="evt.type=container"
-      CONTAINER_OUTPUT="%container.name,%container.image.repository"
-      ${{github.action_path}}/src/run_sysdig.sh filter "/tmp/capture.scap" "$CONTAINER_FILTER" "$CONTAINER_OUTPUT" "/tmp/containers.txt"
-      if [[ -s /tmp/containers.txt ]]; then
-        sort -u -o /tmp/containers.txt /tmp/containers.txt
-        echo "Sorted /tmp/containers.txt"
-      else
-        echo "File /tmp/containers.txt is empty. Impossible to sort it."
-      fi
-      
-
   - name: Retrieve Job Info using GitHub API
     shell: bash
+    if: ${{ inputs.mode == 'live' }}
     env:
       RUN_ID: ${{ github.run_id }}
       REPO: ${{ github.repository }}
     run: |
+      # If we are in live mode, we need to retrieve the job details to get the steps with timestamps
+      # This is useful to understand in which step the security event occured and requires to access the GitHub API
       echo "Retrieving details for run_id=$RUN_ID"
       curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
         -H "Accept: application/vnd.github.v3+json" \
@@ -172,12 +56,10 @@ runs:
         cat steps.json
       fi
       mv steps.json /tmp/steps.json
-      
-  - name: Build summary
+
+  - name: Build Live Summary
+    if: ${{ inputs.mode == 'live' }}
     shell: bash
-    env:
-      RUN_ID: ${{ github.run_id }}
-      REPO: ${{ github.repository }}
     run: |
       python3 -m pip install -r ${{github.action_path}}/src/requirements.txt
       # Falco events
@@ -188,6 +70,7 @@ runs:
         content=$(python3 ${{github.action_path}}/src/falco_events_to_md.py /tmp/falco_events.json /tmp/steps.json)
         echo "$content" >> /tmp/report_output.md
       
+        # Create PR comment with triggered rules, else append to summary
         if ${{ github.event_name == 'pull_request' }}; then
           echo "Creating PR comment with triggered signatures"
           FILE_CONTENT=$(echo "$content" | sed 's/\\/\\\\/g' | sed ':a;N;$!ba;s/\n/\\n/g')
@@ -196,95 +79,43 @@ runs:
             -H "Content-Type: application/json" \
             -d "{\"body\": \"***Falco Rules*** \\n\\n ${FILE_CONTENT} \\n\\n Find out more at https://github.com/$REPO/actions/runs/$RUN_ID\"}" \
             https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments
-        fi
-      fi
-
-      # Processes
-      if [[ -s /tmp/proc.txt ]]; then
-        echo "## Processes" >> /tmp/report_output.md
-        python3 ${{github.action_path}}/src/json_to_md.py /tmp/proc.txt >> /tmp/report_output.md
-      fi
-
-      # Written files
-      if [[ -s /tmp/files_written.txt ]]; then
-        echo "## Written Files" >> /tmp/report_output.md
-        python3 ${{github.action_path}}/src/json_to_md.py /tmp/files_written.txt >> /tmp/report_output.md
-      fi
-
-      # Contacted IPs
-      if [[ -s /tmp/outbound.txt ]]; then
-        echo "## Contacted IPs" >> /tmp/report_output.md
-        if ${{ env.VT_API_KEY != '' }}; then
-          echo "Querying VirusTotal for IPs"
-          python3 ${{github.action_path}}/src/integrations/virustotal/vt_script.py /tmp/outbound.txt --mode ips >> /tmp/outbound_vt.txt
-          python3 ${{github.action_path}}/src/json_to_md.py /tmp/outbound_vt.txt >> /tmp/report_output.md
         else
-          python3 ${{github.action_path}}/src/json_to_md.py /tmp/outbound.txt >> /tmp/report_output.md
+          cat /tmp/report_output.md >> $GITHUB_STEP_SUMMARY
         fi
       fi
+  
+  - name: Upload Capture for Analyze mode
+    if: ${{ inputs.mode == 'analyze' }}
+    uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
+    with:
+      name: capture
+      path: /tmp/capture.scap
 
-      # DNS
-      if [[ -s /tmp/dns_extract_json.txt ]]; then
-        echo "## Contacted DNS Domains" >> /tmp/report_output.md
-        python3 ${{github.action_path}}/src/json_to_md.py /tmp/dns_extract_json.txt >> /tmp/report_output.md
-      fi
-
-      # Containers
-      if [[ -s /tmp/containers.txt ]]; then
-        echo "# Containers" >> /tmp/report_output.md
-        python3 ${{github.action_path}}/src/json_to_md.py /tmp/containers.txt >> /tmp/report_output.md
-      fi
-
-      # Hashes
-      if [[ -s /tmp/hashes.txt ]]; then
-        echo "# Executable Hashes" >> /tmp/report_output.md
-        if ${{ env.VT_API_KEY != '' }}; then
-          echo "Querying VirusTotal for hashes"
-          python3 ${{github.action_path}}/src/integrations/virustotal/vt_script.py /tmp/hashes.txt --mode hashes >> /tmp/hashes_vt.txt
-          python3 ${{github.action_path}}/src/json_to_md.py /tmp/hashes_vt.txt >> /tmp/report_output.md
-        else
-          python3 ${{github.action_path}}/src/json_to_md.py /tmp/hashes.txt >> /tmp/report_output.md
-        fi
-      fi  
-
-      # Top Connections
-      if [[ -s /tmp/top_connection.txt ]]; then
-        echo "## Top Connections" >> /tmp/report_output.md
-        python3 ${{github.action_path}}/src/capture_to_md.py /tmp/top_connection.txt >> /tmp/report_output.md
-      fi
-
-      echo "" >> /tmp/report_output.md
-
-      # If OpenAI API key is set, create a brief summary using OpenAI
-      if ${{ env.OPENAI_API_KEY != '' }}; then
-        echo "Creating Report Summary using OpenAI"
-        echo "# Report Summary" >> $GITHUB_STEP_SUMMARY
-        echo "Installing python dependencies"
-        python3 -m pip install -r ${{github.action_path}}/src/integrations/openai/requirements.txt
-        echo "Calling OpenAI APIs for summary"
-        if ${{inputs.openai-user-prompt == ''}}; then
-          python3 ${{github.action_path}}/src/integrations/openai/create_summary.py /tmp/report_output.md --model "${{inputs.openai-model}}" >> $GITHUB_STEP_SUMMARY
-        else
-          python3 ${{github.action_path}}/src/integrations/openai/create_summary.py /tmp/report_output.md --model "${{inputs.openai-model}}" --user_input "${{inputs.openai-user-prompt}}" >> $GITHUB_STEP_SUMMARY
-        fi
-      fi
-
-      echo "Appending report to github summary"
-      cat /tmp/report_output.md >> $GITHUB_STEP_SUMMARY
-
-  - name: Save captures and events on S3 bucket
-    if: ${{ inputs.save-capture == 'true' && env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != '' && env.S3_BUCKET != ''}}
+  - name: Extract executables' hash
+    if: ${{ inputs.mode == 'analyze' }}
     shell: bash
-    run: |
-      sudo apt-get update
-      sudo apt-get install -y awscli
- 
-      aws configure set aws_access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
-      aws configure set aws_secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}
-      aws configure set default.region ${{ env.AWS_DEFAULT_REGION }}
+    env:
+      VERBOSE: ${{ inputs.verbose }}
+    run: |      
+      # Extract executables' hash. Since hashes are computed afterwards and not by Sysdig, we need to extract them from the runner of this job.
+      # This is workaround, hashes should be computed in real-time by sysdig. Just hash the exepath we know that have been executed for now.
+      ${{github.action_path}}/src/run_sysdig.sh filter "/tmp/capture.scap" "$OUTBOUND_FILTER $CUSTOM_FILTERS" "$OUTBOUND_OUTPUT" "/tmp/proc.txt"
+      cat /tmp/proc.txt | jq '."proc.exepath"' | tr -d "\"" | while read -r file; do
+        if [ -f "$file" ]; then
+            line=$(sha256sum "$file")
+            sha=$(echo "$line" | awk '{print $1}')
+            file=$(echo "$line" | awk '{print $2}')
+            echo "{ \"sha256\": \"$sha\", \"filename\": \"$file\" }"
+        else
+            echo "Warning: File $file does not exist anymore when extracting its SHA256 hash" >&2
+        fi 
+      done > /tmp/hashes.txt
 
-      FOLDER_NAME=$(date +"%Y%m%d_%H%M%S")
-      CAPTURE_FILE_NAME="capture_$FOLDER_NAME.scap"
-      EVENT_FILE_NAME="events_$FOLDER_NAME.json"
-      S3_DESTINATION_FOLDER="s3://${{ env.AWS_S3_BUCKET_NAME }}/$FOLDER_NAME"
-      aws s3 cp /tmp/capture.scap "$S3_DESTINATION_FOLDER/$CAPTURE_FILE_NAME"
+      sort -u -o /tmp/hashes.txt /tmp/hashes.txt
+
+  - name: Upload Hashes
+    if: ${{ inputs.mode == 'analyze' }}
+    uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
+    with:
+      name: hashes
+      path: /tmp/hashes.txt
