update: wait falco container more robustly
Signed-off-by: Lorenzo Susini <susinilorenzo1@gmail.com>

diff --git a/start/action.yaml b/start/action.yaml
--- a/start/action.yaml
+++ b/start/action.yaml
@@ -44,7 +44,19 @@ runs:
         -v /etc:/host/etc:ro \
         falcosecurity/falco-no-driver:${{ inputs.falco-version }} falco -o "json_output=true" -o "file_output.enabled=true" -o "file_output.keep_alive=false" -o "file_output.filename=/tmp/falco_events.json" -o "engine.kind=modern_ebpf"
 
-      sleep 10 # todo(loresuso): replace with a more robust check
+      # Wait for the Falco container to be fully started
+      for i in {1..30}; do
+        if docker ps --filter "name=falco" --filter "status=running" | grep -q falco; then
+          break
+        fi
+        sleep 1
+      done
+
+      if ! docker ps --filter "name=falco" --filter "status=running" | grep -q falco; then
+        echo "Falco container failed to start"
+        exit 1
+      fi
+
       docker logs falco
   
   - name: Start Sysdig capture
