update: wait for sysdig container as well
Signed-off-by: Lorenzo Susini <susinilorenzo1@gmail.com>

diff --git a/start/action.yaml b/start/action.yaml
--- a/start/action.yaml
+++ b/start/action.yaml
@@ -92,17 +92,30 @@ runs:
 
       echo "Creating Sysdig container"
       docker run --rm -d --name sysdig --privileged \
-      -v /var/run/docker.sock:/host/var/run/docker.sock \
-      -v /dev:/host/dev -v /proc:/host/proc:ro \
-      -v /boot:/host/boot:ro \
-      -v /lib/modules:/host/lib/modules:ro \
-      -v /usr:/host/usr:ro \
-      -v /tmp:/tmp \
-      --net=host sysdig/sysdig:latest sysdig --modern-bpf -w /tmp/capture.scap --snaplen=256 "not evt.type in (switch) $IGNORE_SYSCALLS_FILTER"
+        -v /var/run/docker.sock:/host/var/run/docker.sock \
+        -v /dev:/host/dev -v /proc:/host/proc:ro \
+        -v /boot:/host/boot:ro \
+        -v /lib/modules:/host/lib/modules:ro \
+        -v /usr:/host/usr:ro \
+        -v /tmp:/tmp \
+        --net=host sysdig/sysdig:latest sysdig --modern-bpf -w /tmp/capture.scap --snaplen=256 "not evt.type in (switch) $IGNORE_SYSCALLS_FILTER"
       echo "Sysdig started"
 
       # Ensure Sysdig container is running
       sleep 10 # todo(loresuso): replace with a more robust check
+
+      # Wait for the Sysdig container to be fully started
+      for i in {1..30}; do
+        if docker ps --filter "name=sysdig" --filter "status=running" | grep -q sysdig; then
+          break
+        fi
+        sleep 1
+      done
+
+      if ! docker ps --filter "name=sysdig" --filter "status=running" | grep -q sysdig; then
+        echo "Sysdig container failed to start"
+        exit 1
+      fi
 
       if [[ "${{ inputs.verbose }}" == "true" ]]; then
         docker ps -a
